parameters:
    oradmin.admin.handler.login.dispatcher.changeredirection.class: OrApp\OrAdminBundle\EventListener\DispatcherLoginRedirection
    oradmin.admin.handler.login.dispatcher.changeresponse.class: OrApp\OrAdminBundle\EventListener\DispatcherLoginResponse
    
    oradmin.admin.handler.login.class: OrApp\OrAdminBundle\EventListener\HandlerLogin

services:
    #
    # configuration of the pi event classes
    #             
    or_admin.dispatcher.login_handler.change_redirection:
        class: %oradmin.admin.handler.login.dispatcher.changeredirection.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: pi.login.changeredirection, method: onPiLoginChangeRedirection, priority: 1 }  
            
    or_admin.dispatcher.login_handler.change_response:
        class: %oradmin.admin.handler.login.dispatcher.changeresponse.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: pi.login.changeresponse, method: onPiLoginChangeResponse, priority: 1 }
            
    #
    # configuration of the listener classes
    #        
    or_admin.login_handler:
        class: %oradmin.admin.handler.login.class%
        arguments: [@security.context, @event_dispatcher, @doctrine, @service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
