language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install --dev --prefer-dist --no-interaction

script:
  - ./vendor/bin/phing -f build.xml build:jenkins-normal -logger phing.listener.DefaultLogger -DdbUser=$DdbUser -DdbPw=$DdbPw -DdbName=$DdbName